name: $(BuildID)

jobs:

- job: msys2
  pool:
    vmImage: windows-2019
  variables:
    MSYS2_ROOT: $(System.Workfolder)\msys64
    MSYS2_ARCH: x86_64
    COMPILER: gcc
    HTTP_RETRIES: 4
  steps:
    - task: BatchScript@1
      displayName: Setup dependencies
      inputs:
        filename: setup-dependencies.bat
        modifyEnvironment: true
