name: $(BuildID)

jobs:

- job: msys2
  pool:
    vmImage: windows-2019
  variables:
    MSYS2_ROOT: $(System.Workfolder)\msys64
    MSYS2_ARCH: x86_64
    COMPILER: gcc
    HTTP_RETRIES: 4
  steps:
    - pwsh: |
        Invoke-WebRequest -MaximumRetryCount $env:HTTP_RETRIES -OutFile msmpisetup.exe https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe
        Invoke-WebRequest -MaximumRetryCount $env:HTTP_RETRIES -OutFile msmpisdk.msi https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi
        Invoke-WebRequest -MaximumRetryCount $env:HTTP_RETRIES -OutFile python-3.5.4.exe https://www.python.org/ftp/python/3.5.4/python-3.5.4-amd64.exe
        Invoke-WebRequest -MaximumRetryCount $env:HTTP_RETRIES -OutFile python-3.6.8.exe https://www.python.org/ftp/python/3.6.8/python-3.6.8-amd64.exe
        Invoke-WebRequest -MaximumRetryCount $env:HTTP_RETRIES -OutFile python-3.7.7.exe https://www.python.org/ftp/python/3.7.7/python-3.7.7-amd64.exe
        Invoke-WebRequest -MaximumRetryCount $env:HTTP_RETRIES -OutFile python-3.8.2.exe https://www.python.org/ftp/python/3.8.2/python-3.8.2-amd64.exe
      displayName: "Download Installers"
    - script: |
        msmpisetup.exe -unattend -installroot C:\ms-mpi
        msmpisdk.msi /passive
        :: unify installation directory
        rename C:\ms-mpi\Bin  bin
        xcopy.exe "C:\Program Files (x86)\Microsoft SDKs\MPI\Include" "C:\ms-mpi\include\" /s /e /h
        xcopy.exe "C:\Program Files (x86)\Microsoft SDKs\MPI\Lib" "C:\ms-mpi\lib\" /s /e /h
        ::move "C:\Program Files (x86)\Microsoft SDKs\MPI\Include" "C:\ms-mpi\include"
        ::move "C:\Program Files (x86)\Microsoft SDKs\MPI\Lib" "C:\ms-mpi\lib"
        copy "c:\Windows\System32\msmpi.dll" "c:\ms-mpi\lib\x64\msmpi.dll"
        copy "c:\Windows\SysWoW64\msmpi.dll" "c:\ms-mpi\lib\x86\msmpi.dll"
        dir C:\ms-mpi
      displayName: "Install MPI"
    - script: |
        python-3.5.4.exe /quiet InstallAllUsers=1 Include_pip=1 Include_test=0 PrependPath=1
        python-3.6.8.exe /quiet InstallAllUsers=1 Include_pip=1 Include_test=0 PrependPath=1
        python-3.7.7.exe /quiet InstallAllUsers=1 Include_pip=1 Include_test=0 PrependPath=1
        python-3.8.2.exe /quiet InstallAllUsers=1 Include_pip=1 Include_test=0 PrependPath=1
        dir c:\
      displayName: "Install Python"
    - script: |
        choco install msys2 --params="/InstallDir:%MSYS2_ROOT% /NoUpdate /NoPath"
        choco install nsis --params="/S"
      displayName: "Install MSYS2"
    - script: |
        set PATH=%MSYS2_ROOT%\usr\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem
        %MSYS2_ROOT%\usr\bin\pacman --noconfirm -Syyuu
        %MSYS2_ROOT%\usr\bin\pacman --noconfirm -Syuu
      displayName: "Update MSYS2"
    - script: |
        set PATH=%MSYS2_ROOT%\usr\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem
        if %COMPILER%==gcc ( set "TOOLCHAIN=mingw-w64-%MSYS2_ARCH%-toolchain" ) else ( set "TOOLCHAIN=mingw-w64-%MSYS2_ARCH%-clang" )
        %MSYS2_ROOT%\usr\bin\pacman --noconfirm --needed -S ^
        git ^
        zip ^
        unzip ^
        base-devel ^
        mingw-w64-%MSYS2_ARCH%-cmake ^
        mingw-w64-%MSYS2_ARCH%-ncurses ^
        mingw-w64-%MSYS2_ARCH%-readline ^
        mingw-w64-%MSYS2_ARCH%-python2 ^
        mingw-w64-%MSYS2_ARCH%-python3 ^
        mingw64/mingw-w64-%MSYS2_ARCH%-cython ^
        mingw-w64-%MSYS2_ARCH%-python3-setuptools ^
        mingw-w64-%MSYS2_ARCH%-python3-pip ^
        %TOOLCHAIN%
      displayName: "Install MING2 Packages"
    - script: |
        %MSYS2_ROOT%\usr\bin\bash -lc "echo $PWD"
      displayName: "Extra Check"
